import { writable } from "svelte/store"

export const showEncodeForm = writable(true)
export const inputPlainText = writable("")
export const outputEncodedText = writable("")
export const inputEncodedText = writable("")
export const outputDecodedText = writable("")
export const inputPlainTextEncoding = writable("ASCII")
export const inputBase64Encoding = writable("base64url")
export const outputBase64Encoding = writable("base64url")
export const totalBytesOutEncodedText = writable(0)
export const totalBytesInEncodedText = writable(0)
export const totalBytesOutDecodedText = writable(0)
export const inputIsAscii = writable(true)
export const outputIsAscii = writable(true)
export const wasSuccessful = writable(true)
export const errorMessage = writable("")
export const chunks = writable([])
